# Generated by Django 5.0.3 on 2024-05-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_user_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="count",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
