# Generated by Django 5.0.3 on 2024-05-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_user_count"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user", old_name="username", new_name="name",
        ),
        migrations.AddField(
            model_name="user",
            name="visits",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
