# Generated by Django 5.0.3 on 2024-05-04 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_rename_username_user_name_user_visits"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user", old_name="date_joined", new_name="joined",
        ),
    ]
