# Generated by Django 5.0.3 on 2024-05-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_rename_date_joined_user_joined"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="session",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
