# Generated by Django 5.0.3 on 2024-05-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_user_name_alter_user_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="session",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
