# Generated by Django 5.0.3 on 2024-05-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_user_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="speed",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
