# Generated by Django 5.0.3 on 2024-05-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_user_speed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="speed",
            field=models.FloatField(blank=True, default=0),
        ),
    ]
