# Generated by Django 5.0.3 on 2024-05-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="count",
            field=models.ImageField(default=0, upload_to=""),
        ),
    ]
