# Generated by Django 5.0.3 on 2024-05-04 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_user_count"),
    ]

    operations = [
        migrations.DeleteModel(name="User",),
    ]
